proj_name: Diel_18S
scratch:  /vortexfs1/scratch/halexander
sample_suffix: Diel_18S_survey_SCOPE_cruise_July_2015
outputDIR: /vortexfs1/omics/alexander/shu/tagseq-qiime2-snakemake/test/
primerF: CCAGCASCYGCGGTAATTCC
primerR: ACTTTCGTTCTTGATYRA
raw_data: raw_data
manifest: manifest.txt

# QIIME2-specific flags
## Primer removal
primer_err: 0.4
primer_overlap: 3


## DADA2 - ASV flags
truncation_err: 2
truncation_len-f: 200
truncation_len-r: 200
quality_err: 2
training: 1000 #should be set higher for a non-test dataset
chimera: pooled
