proj_name: Diel_18S
scratch:  /vortexfs1/scratch/sarahhu
outputDIR: /vortexfs1/omics/huber/shu/tagseq-qiime2-snakemake
primerF: CCAGCASCYGCGGTAATTCC
primerR: ACTTTCGTTCTTGATYRA
raw_data: raw_data
manifest: manifest.txt
sample_names: SampleList.txt
manifest-trimmed: manifest-trimmed.txt

# QIIME2-specific flags
## Primer removal
primer_err: 0.4
primer_overlap: 3


## DADA2 - ASV flags
truncation_err: 2
truncation_len-f: 200
truncation_len-r: 200
quality_err: 2
training: 1000 #should be set higher for a non-test dataset
chimera: pooled


## Database
database: /vortexfs1/omics/huber/shu/db/pr2-db/V4-pr2_4.11.1-classifier.qza
